apiVersion: apps/v1
kind: Deployment
metadata:
  name: myonlinebooking
spec:
  selector:
    matchLabels:
      app: myonlinebooking
  template:
    metadata:
      labels:
        app: myonlinebooking
    spec:
      containers:
      - name: myonlinebooking
        image: maha4iac/myonlinebooking:1
        ports:
        - containerPort: 8080