apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 3
  selector:
    app: mynginxapp
  template:
    metadata:
      name: mynginxapp
      labels:
        app: mynginxapp
    spec:
      containers:
        - name: mynginxapp
          image: nginx
          ports:
            - containerPort: 80