apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 4
  selector:
    app: myjavaapp
    version: 2.6.2
  template:
    metadata:
      name: myjavaapp
      labels:
       app: myjavaapp
       version: 2.6.2
    spec:
      containers:
       - name: myjavaappcontianer
         image: maha4iac/myonlinebooking:2
         ports:
         - containerPort: 8080