apiVersion: v1
kind: Service
metadata:
  name: mynginxapp-svc
  labels:
    app:  mynginxapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: mynginxapp